#
# version.cmake : version du projet
#

set (LIMA_MAJOR_VERSION "7")
set (LIMA_MINOR_VERSION "10")
set (LIMA_RELEASE_VERSION "0")
set (LIMA_VERSION ${LIMA_MAJOR_VERSION}.${LIMA_MINOR_VERSION}.${LIMA_RELEASE_VERSION})


