#
# version.cmake : version du projet
#

set (LIMA_MAJOR_VERSION "7")
set (LIMA_MINOR_VERSION "11")
set (LIMA_RELEASE_VERSION "1")
set (LIMA_VERSION ${LIMA_MAJOR_VERSION}.${LIMA_MINOR_VERSION}.${LIMA_RELEASE_VERSION})


